enabled_backends = ["arch", "pipx"]
hostname_groups_enabled = true

[arch]
package_manager = "paru"

[hostname_groups]
# Desktop
carbon = ["base", "system", "desktop", "dev", "devops", "gpu-amd", "carbon"]
# Work laptop
tungsten = ["base", "system", "desktop", "dev", "devops", "laptop", "gpu-intel", "tungsten"]
