[options]
# Use our dotfiles pacman.conf instead of /etc/pacman.conf
PacmanConf = /home/lanson/.config/pacman.conf

# Combine AUR and repo upgrades into a single menu
CombinedUpgrade

# Clean build directory after install
CleanAfter
