# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"
# Defaults: https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

[mgr]
# Move cursor
prepend_keymap = [
  { on = "i", run = "arrow prev", desc = "Previous file" },
  { on = "k", run = "arrow next", desc = "Next file" },
  { on = "j", run = "leave", desc = "Back to the parent directory" },
  { on = "l", run = "enter", desc = "Enter the child directory" },
  { on = "<Space>", run = "toggle", desc = "Toggle the current selection state" },
]
