---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  pre-commit-install:
    desc: Install Git pre-commit and commit-msg hooks
    cmds:
      - pre-commit install
      - pre-commit install --hook-type commit-msg
    silent: false

  sudo-install-binary:
    desc: Install binary with sudo using custom installer script
    cmds:
      - |
        sudo bash -c '
          source .bash_config.d/installers.d/utils.sh
          source .bash_config.d/installers.d/install_{{.BIN}}.sh
          install_{{.BIN}} {{.CLI_ARGS}}
        '
    requires:
      vars:
        - BIN
    silent: false

  install-binary:
    desc: Install binary without sudo using custom installer script
    cmds:
      - |
        bash -c '
          source .bash_config.d/installers.d/utils.sh
          source .bash_config.d/installers.d/install_{{.BIN}}.sh
          install_{{.BIN}} {{.CLI_ARGS}}
        '
    requires:
      vars:
        - BIN
    silent: false
